### ISSUE TITLE
could not find driver in EcholinkQsoLog.php

### ISSUE THREAD

**Issue by tamilnaduhams** [guysoft/SvxLinkWrapper#2]
when i run **http://192.168.0.103/EcholinkQsoLog.php** i received a message **could not find driver** in the browser.

**Comment by guysoft** [comment]
You need to install the PDO Sqlite driver, and also apache2 (which I assume you have otherwise you would not get any error at all),

Try running `sudo apt-get update && sudo apt-get install php5-sqlite`

This is indeed missing in the documentation, and I should add it.
(Also you can for and add additions to the documentation if you have any input, the idea is to improve things for others).

**Comment by tamilnaduhams** [comment]
after install php5-sqlite
Error
**SQLSTATE[HY000] [14] unable to open database file**

now i changed the following in **EcholinkQsoLog.php**
**// set path of database file
//$_SERVER['DOCUMENT_ROOT']
$db = "/home/pi/SvxLinkWrapper/EcholinkQsoLog.sqlite";**

now nothing displayed. i think everything fine in php file

**Comment by guysoft** [comment]
@tamilnaduhams Did you mean to close the issue? Have you solved it?
From the error, does `/home/pi/SvxLinkWrapper/EcholinkQsoLog.sqlite` exist?
